Auth/urls.py
from django.urls import path
from .views import authscreen, reguser, regadmin, regsuccess, chooserole, logout

app_name= 'Auth'
urlpatterns = [
    path('', authscreen, name='authscreen'),
    path('register/user/', reguser, name='reguser'),
    path('register/admin/', regadmin, name='regadmin'),
    path('register/success/', regsuccess, name='regsuccesss'),
    path('logout/', logout, name='logout'),
    path('register/choose-role/', chooserole, name='chooserole'),
    
]

Barang/urls.py
from django.urls import path
from .views import barang, detail, add, update, barang_sort_nama, addSubmit, updateSubmit, barang_sort_id, barang_filter, delete

app_name= 'Barang'
urlpatterns = [
    path('', barang, name='barang'),
    path('sort/name', barang_sort_nama, name='barangsortnama'),
    path('sort/id', barang_sort_id, name='barangsortid'),
    path('add/', add, name='add'),
    path('addSubmit/', addSubmit, name='addSubmit'),
    path('detail/<barang>/', detail, name='detail'),
    path('delete/<barang>/', delete, name='delete'),
    path('update/<barang>/', update, name='update'),
    path('updateSubmit/', updateSubmit, name='updateSubmit'),
    path('filter/<kategori>', barang_filter, name='filter'),
    
]

Pesanan/urls.py
from django.urls import path
from .views import buatPesanan, updatePesanan, daftarPesanan, hitungPesanan, daftarkanPesanan, deletePesanan

app_name = 'Pesanan'
urlpatterns = [
	path('buat', buatPesanan, name='buatPesanan'),
	path('update', updatePesanan, name='updatePesanan'),
	path('', daftarPesanan, name='daftarPesanan'),
	path('hitung', hitungPesanan, name='hitungPesanan'),
	path('mendaftar', daftarkanPesanan, name='daftarkanPesanan'),
	path('delete', deletePesanan, name='deletePesanan'),
]

ToysRent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Welcome.urls', namespace='Welcome')),
    path('chat/', include('Chat.urls', namespace='Chat')),
    path('barang/', include('Barang.urls', namespace='Barang')),
    path('auth/', include('Auth.urls', namespace='Auth')),
    path('item/', include('Item.urls', namespace='Item')),
    path('pesanan/', include('Pesanan.urls', namespace='Pesanan')),
    path('level/', include('Level.urls', namespace='Level')),
    path('profile/', include('Profile.urls', namespace='Profile')),
]

Barang/models.py
from django.db import models

# Create your models here.

Barang/forms.py
from django import forms
from django.db import connection

#QUERY ITEM
get_item = '''Select nama from toys_rent.item; '''
with connection.cursor() as cursor:
    cursor.execute(get_item)
    rows = cursor.fetchall()
item= []
for row in rows:
    item.append((row[0], row[0]))
item= tuple(item)

#QUERY PEMILIK
get_pemilik = '''select nama_lengkap from toys_rent.pengguna p, toys_rent.anggota a where a.no_ktp=p.no_ktp;'''
with connection.cursor() as cursor:    
    cursor.execute(get_pemilik)
    row = cursor.fetchall()
pemilik= []
for rows in row:
    pemilik.append((rows[0], rows[0]))
pemilik= tuple(pemilik)

#Query level
get_level=''' select nama_level from toys_rent.level_keanggotaan;'''
with connection.cursor() as cursor: 
    cursor.execute(get_level)
    level = cursor.fetchall()
list_level= []
for rows in level:
    list_level.append(rows[0])

class barangForm(forms.Form):
    id = forms.CharField(label = "Id Barang", required = True, max_length=60, widget=forms.TextInput())
    nama = forms.ChoiceField(label="Nama Item", required = True,choices=item)
    warna = forms.CharField(label = "Warna", required = False, max_length=60, widget=forms.TextInput())
    url = forms.CharField(label = "Url Foto", required = False, max_length=60, widget=forms.TextInput())
    kondisi = forms.CharField(label = "Kondisi", required = True, max_length=60, widget=forms.TextInput())
    penggunaan = forms.CharField(label = "Lama Penggunaan", required = False, widget=forms.NumberInput())
    pemilik = forms.ChoiceField(label="Pemilik/Penyewa", required = True,choices=pemilik)
    def __init__(self, *args, **kwargs):
        super(barangForm, self).__init__(*args, **kwargs)
        for level in list_level:
            royalti_field_name = level
            harga_sewa_field_name = "harga sewa %s" % (level)
            self.fields[royalti_field_name] = forms.IntegerField(label="Persen Royalti")
            self.fields[harga_sewa_field_name] = forms.IntegerField(label="Harga Sewa")

Barang/views.py
from django.shortcuts import render, redirect
from .forms import barangForm
from django.db import  connection

response={}
def barang(request):
    if request.session['role']!='':
        create_table_query = '''Select * from toys_rent.barang; '''
        with connection.cursor() as cursor:
            cursor.execute(create_table_query)
            rows = cursor.fetchall()
            response['barang']=[]
            for row in rows:
                response['barang'].append(row)
        category= '''select nama from toys_rent.kategori'''
        with connection.cursor() as cursor:
            cursor.execute(category)
            kategori= cursor.fetchall()
            response['list_kategori']= []
            for row in kategori:
                response['list_kategori'].append(row[0])
        return render(request, 'barang.html', response)
    else:
        return redirect('Welcome:welcome')

def barang_sort_nama(request):
    if request.session['role']!='':
        
        create_table_query = '''Select * from toys_rent.barang
                                order by toys_rent.barang.nama_item
                                ; '''
        with connection.cursor() as cursor:
            cursor.execute(create_table_query)
            rows = cursor.fetchall()
            print ("\nRows: \n")
            response['barang']=[]
            for row in rows:
                response['barang'].append(row)
        return render(request, 'barang.html', response)
    else:
        return redirect('Welcome:welcome')

def barang_sort_id(request):
    if request.session['role']!='':
        
        create_table_query = '''Select * from toys_rent.barang
                                order by toys_rent.barang.id_barang
                                ;'''
        with connection.cursor() as cursor:
        
            cursor.execute(create_table_query)
            rows = cursor.fetchall()
            print ("\nRows: \n")
            response['barang']=[]
            for row in rows:
                response['barang'].append(row)
          
        return render(request, 'barang.html', response)
    else:
        return redirect('Welcome:welcome')
def barang_filter(request, kategori=None):
    if request.session['role']!='':
        
        kategori="'"+kategori+"'"
        create_table_query = '''Select b.* from toys_rent.barang b, toys_rent.kategori_item k
                                where nama_kategori='''+ kategori +''' and b.nama_item= k.nama_item
                                ; '''
        with connection.cursor() as cursor:
        
            cursor.execute(create_table_query)
            rows = cursor.fetchall()
            print ("\nRows: \n")
            response['barang']=[]
            for row in rows:
                response['barang'].append(row)
        
        return render(request, 'barang.html', response)
    else:
        return redirect('Welcome:welcome')
def detail(request, barang=None):
    if request.session['role']!='':
        
        create_table_query = '''Select nama, lama_penggunaan, warna, deskripsi, bahan, url_foto from toys_rent.barang b ,toys_rent.item i where  nama=b.nama_item and id_barang= '''+ "'"+ barang +"'"+'''; '''
        with connection.cursor() as cursor:
        
            cursor.execute(create_table_query)
            rows = cursor.fetchall()
            print ("\nRows: \n")
            response['barang']=rows[0]

        list_kategori= '''select distinct nama_kategori from toys_rent.kategori_item k, toys_rent.barang b, toys_rent.item i where nama=k.nama_item and b.nama_item=k.nama_item and id_barang= '''+ "'"+ barang +"'"+'''; '''
        with connection.cursor() as cursor:
            cursor.execute(list_kategori)
            kategori = cursor.fetchall()
            response['barang_kategori']=[]
            for i in kategori:
                response['barang_kategori'].append(i[0])
            print(kategori)
        list_review= '''select review from toys_rent.barang_dikirim d where d.id_barang= '''+ "'"+ barang +"'"+ ''';'''
        with connection.cursor() as cursor:
            cursor.execute(list_review)
            list_review = cursor.fetchall()
            response['review']=[]
            print(list_review)
            for i in list_review:
                response['review'].append(i[0])
           
        return render(request, 'detail.html', response)
    else:
        return redirect('Welcome:welcome')
def add(request):
    if request.session['role']=='admin':
        form = barangForm(request.POST or None)
        response['addForm'] = form
        return render(request, 'add.html', response)
    else:
        return redirect('Welcome:welcome')
def addSubmit(request):
    if request.session['role']=='admin':
        
        form= barangForm(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            id = "'"+request.POST['id']+"'"
            nama = "'"+request.POST['nama']+"'"
            warna = "'"+request.POST['warna']+"'"
            url = "'"+request.POST['url']+"'"
            kondisi = "'"+request.POST['kondisi']+ "'"
            penggunaan = request.POST['penggunaan']
            pemilik = "'"+ request.POST['pemilik']+ "'"
            #Query level
            get_level=''' select nama_level from toys_rent.level_keanggotaan;'''
            with connection.cursor() as cursor:
       
                cursor.execute(get_level)
                level = cursor.fetchall()
                list_level= []
                for rows in level:
                    list_level.append(rows[0])
                kategori_dict={}
                for i in list_level:
                    kategori_dict[i]={
                        i: request.POST[i],
                        "Sewa"+i:request.POST["harga sewa "+i]
                    }
                
                print(kategori_dict)
            get_pemilik = '''select no_ktp from toys_rent.pengguna p where p.nama_lengkap='''+pemilik +''';'''
            with connection.cursor() as cursor:
                cursor.execute(get_pemilik)
                ktp = "'"+ cursor.fetchall()[0][0]+"'"
                print(ktp)     
            query= '''insert into toys_rent.barang values('''+id+''','''+ nama+''','''+warna+''','''+url+''','''+kondisi+''','''+penggunaan+''','''+ktp +'''); '''
            with connection.cursor() as cursor:
                cursor.execute(query)
            with connection.cursor() as cursor:
                for i in kategori_dict:
                    print(i)
                    print(kategori_dict[i])
                    print(kategori_dict[i][i])
                    print(kategori_dict[i]["Sewa"+i])
                    cursor.execute('''insert into toys_rent.info_barang_level values('''+id+''','''+"'"+i+"'"+''', '''+"'"+kategori_dict[i]["Sewa"+i]+"'"+''','''+"'"+kategori_dict[i][i]+"'"+ ''') ''')
                    print(i)
                    print(kategori_dict[i])  
            connection.commit()
            return redirect('Barang:barang')
        else:
            return redirect('Barang:add',)
    else:
        return redirect('Welcome:welcome')
def delete(request,barang=None):
    if request.session['role']=='admin':
        
        print(barang)
        barang= "'"+ barang + "'"
        del_barang = '''delete from toys_rent.barang b where b.id_barang= '''+barang +''';'''
        with connection.cursor() as cursor:       
            cursor.execute(del_barang)
        connection.commit()
        return redirect('Barang:barang')
    else:
        return redirect('Welcome:welcome')

def update(request, barang=None):
    if request.session['role']=='admin':
    
        barang= "'"+ barang + "'"
        get_barang = '''select * from toys_rent.barang b where b.id_barang= '''+barang +''';'''
        with connection.cursor() as cursor: 
            cursor.execute(get_barang)
            barangs=cursor.fetchall()[0]    
        ktp= "'"+barangs[6]+"'"
        get_pemilik = '''select nama_lengkap from toys_rent.pengguna p where p.no_ktp='''+ktp +''';'''
        with connection.cursor() as cursor:       
            cursor.execute(get_pemilik)
            pemilik=cursor.fetchall()[0]
        get_level='''select nama_level,harga_sewa,porsi_royalti from toys_rent.info_barang_level i, toys_rent.barang b where b.id_barang=i.id_barang and b.id_barang='''+barang+''';'''
        with connection.cursor() as cursor:
            cursor.execute(get_level)
            level=cursor.fetchall()
        lis={
            "id":barangs[0],
            "nama":barangs[1],
            "warna":barangs[2],
            "url":barangs[3],
            "kondisi":barangs[4],
            "penggunaan":barangs[5],
            "pemilik":pemilik,    
        }
        for i in level:
                lis[i[0]]= i[2]
                lis["harga sewa "+i[0]]=i[1]
        
        form = barangForm(request.POST or None, initial=lis)
        response['updateForm'] = form
        return render(request, 'update.html', response)
    else:
        return redirect('Welcome:welcome')
def updateSubmit(request):
    if request.session['role']=='admin':
        form= barangForm(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            id = "'"+request.POST['id']+"'"
            nama = "'"+request.POST['nama']+"'"
            warna = "'"+request.POST['warna']+"'"
            url = "'"+request.POST['url']+"'"
            kondisi = "'"+request.POST['kondisi']+ "'"
            penggunaan = request.POST['penggunaan']
            pemilik = "'"+ request.POST['pemilik']+ "'"
            #Query level
            get_level=''' select nama_level from toys_rent.level_keanggotaan;'''
            with connection.cursor() as cursor:
                cursor.execute(get_level)
                level = cursor.fetchall()
            list_level= []
            for rows in level:
                list_level.append(rows[0])
            kategori_dict={}
            for i in list_level:

Barang/templates/add.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<center>
	<div class="form-style-5">
            <h1 style='margin-top:25px;margin-bottom:50px;'>Add toys</h1>
            <form  method="POST" action="{% url 'Barang:addSubmit' %}">
            {% csrf_token %}
            {% for field in addForm %}
                <p class="label_tag">
                    {% if  'Persen Royalti' in field.label %}
                        <strong>+{{field.name}}</strong>   
                        {{ field.label_tag }} 
                        {{field}}
                    {% else %}
                        {{ field.label_tag }} 
                        {{ field }}
                    {% endif %}
                </p>
            {% endfor %}
            <input style="margin-bottom:10px" class="btn btn-info btn-lg" id="submit"  type="submit" value="Submit" >
         </form>
	</div>
</center>
{% endblock %} 

Barang/templates/barang.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

<link rel="stylesheet" href="{% static 'css/barang.css' %}" type="text/css">
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" ></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

<p>
  <center>
    <h1>Our Toys</h1> 
        
  </center>
  
</p>
  <div class="dropdown" id="filter" >
    <button  class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Category
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      {%for i in list_kategori%}
        <a class="dropdown-item" href="{% url 'Barang:filter' i %}">{{i}}</a>
      {% endfor %}
    </div>
  </div>
  <div class="dropdown" id="sort">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sort by
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="{% url 'Barang:barangsortnama' %}">Name</a>
      <a class="dropdown-item" href="{% url 'Barang:barangsortid' %}">Id</a>
    </div>
  </div>
<div style="overflow-x:auto;">
  <table class="table table-hover" id="tables" style="text-align:center">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Color</th>
        <th scope="col">Condition</th>
        <th scope="col"> </th>
        <th scope="col"> </th>
        {% if request.session.role == "admin" %}
        <th scope="col"><a href="{% url 'Barang:add' %}"><button class="icon-btn add-btn">
            <div class="add-icon"></div>
            <div class="btn-txt">Add</div>
          </button></a> </th>
        {%endif%}
      </tr>
    </thead>
    <tbody>
  {%for i in barang%}
      <tr>
        <th scope="row">{{i.0}}</th>
        <td>{{i.1}}</td>
        <td>{{i.2}}</td>
        <td>{{i.4}}</td>
        <td>
            <a href="{% url 'Barang:detail' i.0 %}"><button  type="button" class="btn btn-primary" >Detail</button></a>
        </td>
        {% if request.session.role == "admin" %}
        <td>
          <a href="{% url 'Barang:update' i.0 %}"><button type="button" class="btn btn-warning" style="width:70px">Update</button></a>
          <button onclick='del({{i.0}})' type="button" class="btn btn-danger" style="width: 70px;">Delete</button>
        </td>
        {%endif%}
        <td>
          <img id={{i.0}} src="{% static 'photos/shopping.ico' %}" style="width:40px" onclick="ganti('{{i.0}}')">
        </td>
      </tr>
      {% endfor %}
      <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>Total</td>
          <td class="bg-success" style="color:white">{{barang|length}}</td>
      </tr>
    </tbody>
  </table>

<script>
$(document).ready( function () {
    $('#tables').DataTable(
      {
        "dom": '<"top"f>rt<"bottom"p><"clear">',
        "ordering": false,
        "searching": false,
        "info":     false,
        

    }
    );
} );
function del(id) {
  if (confirm("Apakah anda yakin menghapus barang ini?")){
    var url = "{% url 'Barang:delete' 'id' %}";
    document.location.href = url.replace('id', id);
  }
};
function ganti(ids) {
  
  if (document.getElementById(ids).src.includes('ico')){
    document.getElementById(ids).src = "{% static 'photos/shopping-after.png' %}";
    alert("Kamu menandai barang ini");
  }
  else{
    document.getElementById(ids).src= "{% static 'photos/shopping.ico' %}"
  }
}
</script>
{% endblock %} 

Barang/templates/detail.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="container-fluid bg-3 text-center" style="margin-top:50px; margin-bottom: 50px" id='details'>
		<div class="row">
			<div  class="col-sm col-md">
				<img class="image" src="{{barang.5}}" style="
				box-shadow: 5px 5px  grey;">
				<h6>{{barang.5}}</h6>
			</div>
			<div  class="col-sm col-md" style="margin-top:100px">
				<h1>{{barang.0}} </h1>
				<h4>Umur: {{barang.1}}</h4>
				<h5>Warna: {{barang.2}}</h5>
				<h5>Deskripsi: {{barang.3}}</h5>
				<h5>Material: {{barang.4}}</h5>
				<div>
					{% for i in barang_kategori%}
						<label style="border-radius:20px; background-color:rgb(197, 191, 191)">{{i}}</label>
					{%endfor%}

				</div>
				<a href="{% url 'Pesanan:buatPesanan' %}"><button  type="button" class="btn btn-primary" >Rent now!</button></a>
				<div style="margin-top:20px">
					<h3><u>Review</u></h3>
					{% for i in review%}
					{{i}}
					{%endfor%}
				</div>
			</div>
		</div>
	
{% endblock %} 

Barang/templates/update.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<center>
	<div class="form-style-5">
            <h1 style='margin-top:25px;margin-bottom:50px;'>Change toys</h1>
            <form  method="POST" action="{% url 'Barang:updateSubmit' %}">
            {% csrf_token %}
            {% for field in updateForm %}
                <p class="label_tag">
                    {% if  'Persen Royalti' in field.label   %}
                        <strong>+{{field.name}}</strong>   
                        {{ field.label_tag }} 
                        {{field}}
                    {% else %}
                        {{ field.label_tag }} 
                        {{ field }}
                    {% endif %}
                </p>
            {% endfor %}
            <input style="margin-bottom:10px" class="btn btn-info btn-lg" id="submit"  type="submit" value="Submit" >
         </form>
	</div>
</center>
{% endblock %} 