Auth/urls.py
from django.urls import path
from .views import authscreen, reguser, regadmin, regsuccess, chooserole, logout

app_name= 'Auth'
urlpatterns = [
    path('', authscreen, name='authscreen'),
    path('register/user/', reguser, name='reguser'),
    path('register/admin/', regadmin, name='regadmin'),
    path('register/success/', regsuccess, name='regsuccesss'),
    path('logout/', logout, name='logout'),
    path('register/choose-role/', chooserole, name='chooserole'),
    
]

Level/urls.py
from django.urls import path
from .views import buatLevel, updateLevel, daftarLevel, deleteLevel

app_name = 'Level'
urlpatterns = [
	path('buat', buatLevel, name='buatLevel'),
	path('update', updateLevel, name='updateLevel'),
	path('', daftarLevel, name='daftarLevel'),
	path('delete', deleteLevel, name='deleteLevel'),
]

ToysRent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Welcome.urls', namespace='Welcome')),
    path('chat/', include('Chat.urls', namespace='Chat')),
    path('barang/', include('Barang.urls', namespace='Barang')),
    path('auth/', include('Auth.urls', namespace='Auth')),
    path('item/', include('Item.urls', namespace='Item')),
    path('pesanan/', include('Pesanan.urls', namespace='Pesanan')),
    path('level/', include('Level.urls', namespace='Level')),
    path('profile/', include('Profile.urls', namespace='Profile')),
]

Level/models.py
from django.db import models

# Create your models here.

Level/forms.py
from django import forms

class LevelForm(forms.Form):
	levelName = forms.CharField(max_length=20, required=True, label='Nama Level',
		widget=forms.TextInput(attrs={'placeholder': 'Masukkan nama level...'}))
	minPoin = forms.IntegerField(required=True, label='Minimum Poin',
		widget=forms.NumberInput(attrs={'placeholder': 'Masukkan minimum poin...', 'min':0}))
	desc = forms.CharField(label='Deskripsi',
		widget=forms.TextInput(attrs={'placeholder': 'Masukkan deskripsi...'}))

Level/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import LevelForm
from django.db import connection

import os
import psycopg2

response = {}
def buatLevel(request):
	if request.session['role']=='admin':
		if request.method == 'POST':		
			levelName = request.POST['levelName']
			minPoin = float(request.POST['minPoin'])
			desc = request.POST['desc']
			
			with connection.cursor() as cursor:
				cursor.execute('''SET SEARCH_PATH TO TOYS_RENT ''')
				query = '''INSERT INTO LEVEL_KEANGGOTAAN VALUES(%s, %s, %s);'''
				cursor.execute(query, (levelName, minPoin, desc))
				connection.commit()
			return redirect('/level')

		response['form'] = LevelForm
		return render(request, 'buat-level.html', response)
	else:
		return redirect('Welcome:welcome')

def updateLevel(request):
	if request.session['role']=='admin':
		if request.method == 'POST':
			with connection.cursor() as cursor:
				cursor.execute('''SET SEARCH_PATH TO TOYS_RENT ''')
				levelName = request.POST['init_name'] #default level name
				if request.POST['levelName'] != request.POST['init_name']:
					query = '''UPDATE LEVEL_KEANGGOTAAN SET nama_level=%s WHERE nama_level=%s;'''
					cursor.execute(query, (request.POST['levelName'], levelName))
					levelName =  request.POST['levelName'] #new level name
				if request.POST['minPoin'] != request.POST['init_poin']:
					query = '''UPDATE LEVEL_KEANGGOTAAN SET minimum_poin=%s WHERE nama_level=%s;'''
					cursor.execute(query, (request.POST['minPoin'], levelName))
				if request.POST['desc'] != request.POST['init_desc']:
					query = '''UPDATE LEVEL_KEANGGOTAAN SET deskripsi=%s WHERE nama_level=%s;'''
					cursor.execute(query, (request.POST['desc'], levelName))
				connection.commit()
			return redirect('/level')

		data = {'levelName':request.GET['level'],
		'minPoin':request.GET['poin'],
		'desc':request.GET['desc']
		}
		form = LevelForm(initial=data)

		response = {'form':form,
		'initial_name':request.GET['level'],
		'initial_poin':request.GET['poin'],
		'initial_desc':request.GET['desc']
		}
		return render(request, 'update-level.html', response)
	else:
		return redirect('Welcome:welcome')

def daftarLevel(request):
	if request.session['role']=='admin':
		with connection.cursor() as cursor:
			cursor.execute('''SET SEARCH_PATH TO TOYS_RENT ''')
			query = '''SELECT * FROM LEVEL_KEANGGOTAAN ORDER BY minimum_poin;'''
			cursor.execute(query)
			rows = cursor.fetchall()
			
			response['level'] = []
			for row in rows:
				response['level'].append(row)

		return render(request, 'daftar-level.html', response)
	else:
		return redirect('Welcome:welcome')

def deleteLevel(request):
	if request.session['role']=='admin':
		with connection.cursor() as cursor:
			cursor.execute('''SET SEARCH_PATH TO TOYS_RENT ''')
			levelName = request.GET['level']
			query = '''DELETE FROM LEVEL_KEANGGOTAAN 
					WHERE nama_level=%s;'''
			cursor.execute(query, (levelName,))
			connection.commit()
		return redirect('/level')
	else:
		return redirect('Welcome:welcome')

Level/templates/buat-level.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<body>
	<div class="container">
		<div class="row justify-content-center" style="border: solid; border-color: red; border-radius: 30px; margin: 20px; margin-bottom: 40px;">
			<div class="col-lg-12">
				<p class="text-center font-weight-bold" style="font-size: 7vw;">Form Tambah Level</p>
			</div>
			<div class="col-lg-12" style="margin: 10px">				
				<form action="" method="POST">
					{% csrf_token %}
					<div class="col-lg-12">
						{{ form.as_p }}
					</div>				
					<div class="text-center col-lg-12" style="margin: 10px">
						<button type="submit" class="btn btn-md btn-danger" id="tambah-level" action="POST">Tambah</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</body>
{% endblock %}

Level/templates/daftar-level.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<body>	
	<div class="container">
		<div class="row justify-content-center" style="border: solid; border-color: red; border-radius: 30px; margin: 20px; margin-bottom: 40px;">
			<div class="col-lg-12">
				<p class="text-center font-weight-bold" style="font-size: 7vw;">Daftar Level</p>
			</div>
			<div class="col-lg-12 text-right" style="margin-bottom: 5px;">
				<a href="{% url 'Level:buatLevel'%}"  class="btn btn-sm btn-danger" role="button" aria-pressed="true">Add</a>
			</div>
			<div class="text-center col-lg-12">
				<table class="table">
					<thead>
						<tr>
							<th scope="col">No</th>
							<th scope="col">Nama level</th>
							<th scope="col">Deskripsi</th>
							<th scope="col">Minimum poin</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						{% for i in level%}
						<tr>
							<th scope="row">{{ forloop.counter }}</th>
							<td>{{i.0}}</td>
							<td>{{i.2}}</td>
							<td>{{i.1}}</td>
							<td>
								<button onclick="window.location.href='{% url 'Level:updateLevel' %}?level={{i.0}}&poin={{i.1}}&desc={{i.2}}'" class="btn btn-sm btn-danger">Update</button>
								<button type="button" class="btn btn-sm btn-outline-danger" data="{{i.0}}" onclick="deleteLevel(this.getAttribute('data'))">Delete</button>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div> 		
	</div>
</body>
<script>
	function deleteLevel(data){		
		result = confirm("Are you sure you want to delete this?")
		if(result){
			$.ajax({
				method: 'GET',
				url: '/level/delete',
				data: {'level':data},
				success: function(data){
					alert("Deleted.");
					window.location.href="{% url 'Level:daftarLevel'%}";
				}
			})
		}
	}
</script>
{% endblock %}

Level/templates/update-level.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<body>
	<div class="container">
		<div class="row justify-content-center" style="border: solid; border-color: red; border-radius: 30px; margin: 20px; margin-bottom: 40px;">
			<div class="col-lg-12">
				<p class="text-center font-weight-bold" style="font-size: 7vw;">Form Update Level</p>
			</div>
			<div class="col-lg-12" style="margin: 10px">
				<form action="" method="POST">
					{% csrf_token %}
					<div class="col-lg-12">
						{{ form.as_p }}
						<input type="hidden" name="init_name" value="{{initial_name}}">
						<input type="hidden" name="init_poin" value="{{initial_poin}}">
						<input type="hidden" name="init_desc" value="{{initial_desc}}">
					</div>				
					<div class="text-center col-lg-12" style="margin: 10px">
						<button type="submit" class="btn btn-md btn-danger">Update</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</body>
{% endblock %}