Auth/urls.py
from django.urls import path
from .views import authscreen, reguser, regadmin, regsuccess, chooserole, logout

app_name= 'Auth'
urlpatterns = [
    path('', authscreen, name='authscreen'),
    path('register/user/', reguser, name='reguser'),
    path('register/admin/', regadmin, name='regadmin'),
    path('register/success/', regsuccess, name='regsuccesss'),
    path('logout/', logout, name='logout'),
    path('register/choose-role/', chooserole, name='chooserole'),
    
]

Chat/urls.py
from django.urls import path
from .views import chat,chatUser, chatbox,send, sendUser

app_name= 'Chat'
urlpatterns = [
    path('admin/', chat, name='admin'),
    path('', chatUser, name='chat'),
    path('<ktp>', chatbox, name='box'),
    path('send/<ktp>', send, name='send'),
    path('sendUser/', sendUser, name='sendUser')
    
]

ToysRent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Welcome.urls', namespace='Welcome')),
    path('chat/', include('Chat.urls', namespace='Chat')),
    path('barang/', include('Barang.urls', namespace='Barang')),
    path('auth/', include('Auth.urls', namespace='Auth')),
    path('item/', include('Item.urls', namespace='Item')),
    path('pesanan/', include('Pesanan.urls', namespace='Pesanan')),
    path('level/', include('Level.urls', namespace='Level')),
    path('profile/', include('Profile.urls', namespace='Profile')),
]

Chat/models.py
from django.db import models

# Create your models here.

Chat/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
import string, random, datetime
from django.db import  connection

def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))



response={}
def chatUser(request):
    if request.session['role']=='anggota':
        ktp= "'"+ request.session['no_ktp']+ "'"
        create_table_query = '''Select distinct pesan, date_time, nama_lengkap, no_ktp_anggota from toys_rent.chat c, toys_rent.pengguna p where no_ktp_anggota='''+ ktp +''' and p.no_ktp=no_ktp_anggota  order by date_time; '''
        with connection.cursor() as cursor:
            cursor.execute(create_table_query)
            rows = cursor.fetchall()
        list_chat=[]
        for i in rows:
            list_chat.append([i[0], i[1], i[2], i[3]])
        response['chat']=list_chat
        return render(request, 'chatUser.html', response)   
    elif request.session['role']=='admin':
        return redirect('Chat:admin')
    else:
        return redirect('Welcome:welcome')
        
def chat(request):
    if request.session['role']=='anggota':
        return redirect('Chat:chat') 
    elif request.session['role']=='admin':
        create_table_query = '''Select distinct nama_lengkap, p.no_ktp from toys_rent.pengguna p, toys_rent.chat c where c.no_ktp_anggota=p.no_ktp; '''
        with connection.cursor() as cursor:
            cursor.execute(create_table_query)
            rows = cursor.fetchall()
        list_pengguna=[]
        for i in rows:
            list_pengguna.append([i[0], i[1]])
        response['list']=list_pengguna
        
        return render(request, 'chat.html', response)
       
    else:
        return redirect('Welcome:welcome')

def chatbox(request, ktp=None):
 
    response['ktp']=ktp
    ktp="'"+ ktp  + "'"
    ktp_admin= "'"+ request.session['no_ktp']+ "'"
    print(ktp_admin)
    if request.session['role']=='anggota':
        return redirect('Chat:chat') 
    elif request.session['role']=='admin':
        create_table_query = '''Select distinct pesan, date_time, nama_lengkap, no_ktp_anggota from toys_rent.chat c, toys_rent.pengguna p where no_ktp_anggota='''+ ktp +''' and p.no_ktp=no_ktp_anggota and no_ktp_admin='''+ktp_admin +'''  order by date_time; '''
        with connection.cursor() as cursor:
            cursor.execute(create_table_query)
            rows = cursor.fetchall()
        list_chat=[]
        for i in rows:
            list_chat.append([i[0], i[1], i[2], i[3]])
        response['chat']=list_chat
        
        return render(request, 'chatbox.html', response)
    else:
        return redirect('Welcome:welcome')

def send(request, ktp=None):
    isi_pesan= "'"+request.POST['isi']+"'"
    id="'" + id_generator() +"'"
    ktp_anggota="'"+ktp+"'"
    ktp_admin= "'"+ request.session['no_ktp']+ "'"
    date_time= datetime.datetime.now()
    date_time=date_time.strftime('%Y-%m-%d %H:%M:%S')
    date_time= "'"+date_time+"'"
    query = '''insert into toys_rent.chat values ('''+id+''','''+isi_pesan+''','''+date_time+''','''+ktp_anggota+''','''+ktp_admin+'''); '''
    with connection.cursor() as cursor:
        cursor.execute(query)
    connection.commit()
    return redirect("/chat/"+ktp)

def sendUser(request):
    isi_pesan= "'"+request.POST['isi']+"'"
    id="'" + id_generator() +"'"
    ktp_admin="'1234567894'"
    ktp_anggota= "'"+ request.session['no_ktp']+ "'"
    date_time= datetime.datetime.now()
    date_time=date_time.strftime('%Y-%m-%d %H:%M:%S')
    date_time= "'"+date_time+"'"
    query = '''insert into toys_rent.chat values ('''+id+''','''+isi_pesan+''','''+date_time+''','''+ktp_anggota+''','''+ktp_admin+'''); '''
    with connection.cursor() as cursor:
        cursor.execute(query)
    connection.commit()
    return redirect('Chat:chat')

Chat/templates/chat.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/chat.css' %}" type="text/css">
<body>
  <center><h1>Room Chat</h1></center>
<div class="container">
<div class="messaging">
          <div class="inbox_chat"> 
           {%for i in list%}
            <a href="{% url 'Chat:box' i.1 %}"><div class="chat_list" id= {{i.1}}>
              <div class="chat_people">
                <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                <div class="chat_ib">
                  <h5>{{i.0}}</h5>
                </div>
              </div>
              </div>
            </a>
            {%endfor%}
          </div>
    </div>
    </body>
    </html>
{% endblock %} 

Chat/templates/chatUser.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/chat.css' %}" type="text/css">
<body>
<center><strong>Chat</strong></center>
<div class="container">
  <div class="messaging">
      {%for i in chat%}         
      <div >                     
        <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
        
        <div class="chat_ib" style="margin-bottom: 100px">
          <h5>{{i.2}} <span class="chat_date">{{i.1}}</span></h5>
          <p>{{i.0}}</p>
        </div>
      </div>
    
    {%endfor%}
    <div class="input_msg_write">
      <form  method="POST" action="{% url 'Chat:sendUser' %}">
        {% csrf_token %}
        <input name="isi" style="background-color:#cecbcc; border-radius: 10px; margin-top: 10px" type="text" class="write_msg" placeholder="Type a message" />
      </form>
    </div>
  </div>
</div>
</body>
</html>
{% endblock %} 

Chat/templates/chatbox.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/chat.css' %}" type="text/css">
<body>
<center><strong>Chat</strong></center>
<div class="container">
  <div class="messaging">
      {%for i in chat%}         
      <div >                     
        <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
        
        <div class="chat_ib" style="margin-bottom: 100px">
          <h5>{{i.2}} <span class="chat_date">{{i.1}}</span></h5>
          <p>{{i.0}}</p>
        </div>
      </div>
    
    {%endfor%}
    <div class="input_msg_write">
      <form  method="POST" action="{% url 'Chat:send' ktp %}">
        {% csrf_token %}
        <input name="isi" style="background-color:#cecbcc; border-radius: 10px; margin-top: 10px" type="text" class="write_msg" placeholder="Type a message" />
      </form>
    </div>
  </div>
</div>
</body>
</html>
{% endblock %} 