Auth/urls.py
from django.urls import path
from .views import authscreen, reguser, regadmin, regsuccess, chooserole, logout

app_name= 'Auth'
urlpatterns = [
    path('', authscreen, name='authscreen'),
    path('register/user/', reguser, name='reguser'),
    path('register/admin/', regadmin, name='regadmin'),
    path('register/success/', regsuccess, name='regsuccesss'),
    path('logout/', logout, name='logout'),
    path('register/choose-role/', chooserole, name='chooserole'),
    
]

Barang/urls.py
from django.urls import path
from .views import barang, detail, add, update, barang_sort_nama, addSubmit, updateSubmit, barang_sort_id, barang_filter, delete

app_name= 'Barang'
urlpatterns = [
    path('', barang, name='barang'),
    path('sort/name', barang_sort_nama, name='barangsortnama'),
    path('sort/id', barang_sort_id, name='barangsortid'),
    path('add/', add, name='add'),
    path('addSubmit/', addSubmit, name='addSubmit'),
    path('detail/<barang>/', detail, name='detail'),
    path('delete/<barang>/', delete, name='delete'),
    path('update/<barang>/', update, name='update'),
    path('updateSubmit/', updateSubmit, name='updateSubmit'),
    path('filter/<kategori>', barang_filter, name='filter'),
    
]

Chat/urls.py
from django.urls import path
from .views import chat,chatUser, chatbox,send, sendUser

app_name= 'Chat'
urlpatterns = [
    path('admin/', chat, name='admin'),
    path('', chatUser, name='chat'),
    path('<ktp>', chatbox, name='box'),
    path('send/<ktp>', send, name='send'),
    path('sendUser/', sendUser, name='sendUser')
    
]

Item/urls.py
from django.urls import path
from .views import displayitems, additem, updateitem, deleteitem, displaybarang

app_name= "Item"
urlpatterns = [
    path('', displayitems, name='displayitems'),
    path('filter/<category>/', displayitems, name='filterbycategory'),
    path('sort/<sortby>/', displayitems, name='sortby'),
    path('add/', additem, name='additem'),
    path('update/', updateitem, name='update'),
    path('update/<name>/', updateitem, name='updateitem'),
    path('delete/<name>/', deleteitem, name='deleteitem'),
    path('displaybarang/<item_name>/', displaybarang, name='displaybarang')
]

Level/urls.py
from django.urls import path
from .views import buatLevel, updateLevel, daftarLevel, deleteLevel

app_name = 'Level'
urlpatterns = [
	path('buat', buatLevel, name='buatLevel'),
	path('update', updateLevel, name='updateLevel'),
	path('', daftarLevel, name='daftarLevel'),
	path('delete', deleteLevel, name='deleteLevel'),
]

ToysRent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Welcome.urls', namespace='Welcome')),
    path('chat/', include('Chat.urls', namespace='Chat')),
    path('barang/', include('Barang.urls', namespace='Barang')),
    path('auth/', include('Auth.urls', namespace='Auth')),
    path('item/', include('Item.urls', namespace='Item')),
    path('pesanan/', include('Pesanan.urls', namespace='Pesanan')),
    path('level/', include('Level.urls', namespace='Level')),
    path('profile/', include('Profile.urls', namespace='Profile')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Toys Rent Corp.</title>
		<meta name="google-signin-client_id" content="793165754584-h9e13uhc75eg0n44drobf3m04rr2h5nt.apps.googleusercontent.com">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script src="https://apis.google.com/js/platform.js" async defer></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css" />
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
        <link href="https://fonts.googleapis.com/css?family=Crete+Round|Pacifico" rel="stylesheet">
        <!--Insert CSS Tiap page here-->
        <link rel="stylesheet" href="{% static 'css/authscreen.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/item.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/welcome.css' %}" type="text/css">
        
        <link rel="stylesheet" href="{% static 'css/add.css' %}" type="text/css">
    
    
    
    </head>
    <body>
        <!--NAVBAR-->
        <nav class="navbar navbar-expand-lg navbar-light" style="background:#e84a4a ">
                <a class="navbar-brand active" href="{% url 'Welcome:welcome' %}"><img src="{% static 'photos/logo-web.png' %}" style="width:80px;"><span class="sr-only">(current)</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        {% if request.session.role == "anggota" %}
                            <li class="nav-item  events_news_font" style="margin-right:8px">
                                    <a class="nav-link" href="{% url 'Item:displayitems' %}">Items</a>
                            </li >

                        <li class="nav-item  events_news_font">
                            <a class="nav-link" href="{% url 'Barang:barang' %}">Barang</a>
                        </li>
                        <li class="nav-item  events_news_font" style="margin-right:8px">
                                <a class="nav-link" href="{% url 'Chat:chat' %}">Chat</a>
                        </li >

                            <li class="nav-item  events_news_font" style="margin-right:8px">
                                    <a class="nav-link" href="{% url 'Pesanan:daftarPesanan' %}">Pesanan</a>
                            </li >

                        {% elif request.session.role == "admin" %}
                            <li class="nav-item  events_news_font" style="margin-right:8px">
                                    <a class="nav-link" href="{% url 'Item:displayitems' %}">Items</a>
                            </li >

                            <li class="nav-item  events_news_font">
                                <a class="nav-link" href="{% url 'Barang:barang' %}">Barang</a>
                            </li>
                            <li class="nav-item  events_news_font" style="margin-right:8px">
                                    <a class="nav-link" href="{% url 'Chat:chat' %}">Chat</a>
                            </li >

                            <li class="nav-item  events_news_font" style="margin-right:8px">
                                    <a class="nav-link" href="{% url 'Pesanan:daftarPesanan' %}">Pesanan</a>
                            </li >
                            <li class="nav-item  events_news_font" style="margin-right:8px">
                                    <a class="nav-link" href="{% url 'Level:daftarLevel' %}">Level</a>
                            </li >
                        {% endif %}

						{% if request.session.role == "admin" or request.session.role == "anggota" %}
                            <li class="nav-item  events_news_font" style="margin-right:8px">
                                    <a class="nav-link" href="{% url 'Profile:viewprofile' %}">{{ request.session.nama }}</a>
                            </li >

                            <li class="nav-item  events_news_font" style="margin-right:8px">
                                    <a class="nav-link" href="{% url 'Auth:logout' %}">|Logout|</a>
                            </li >
                        {% else %}
                            <li class="nav-item  events_news_font" style="margin-right:8px">
                                    <a class="nav-link" href="{% url 'Auth:authscreen' %}">Login</a>
                            </li >
                        {% endif %}
						
                    </ul>
                </div>
        </nav>

        {% block content %}
        {% endblock %}

    <!-- FOOTER -->
	<footer id="myFooter">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 img-responsive center text-center">
                    <div class="col-sm-12 copyright">
                            <p>Copyright © 2019 Toys Rent Corp. All rights reserved</p> 
                    </div>
                </div>
				</div>
            </div>
        </div>
    </footer>
    </body>
</html>